### ISSUE TITLE
TODO - UI pass and general improvement of the Contacts Dashboard

### ISSUE THREAD

**Issue by jamieaa64** [FreelyGive/contacts#22]
**Reasons why we're doing it**
Make it good enough by Adrian's definition  for the first run of the demos

Ready To work

**Demo Content**
- [x] Capitalise the cities
- [x] Add a mobile field and generate some random numbers (starting 0700)

**Changes on both pages**

- [x] Add a nice "Company logo" on the top left that adrian finds (Link below)
- [x] Remove page breadcrumbs on Dashboard
- [x] Switch the profile photo back to square as per petes design
- [x] Change Individual to People and person. And Organisation to Organisations/Organisation.
- [x] The standard text font Pete uses looks better
- [x] Normal users shouldn't be able to edit views.
- [x] Sizing issues of photos

**Contacts Listing**

- [x] Move the roles information to be under the other information as per pete's designs
- [x] Bump the pager limit up to 20
- [x] How to manage ‘next/prev’
- [x] Change the "Authenticated User" role to be "User Account"
- [x] Layout of the facets, should match pete's styling
- [x] Change the title of the page from "Contacts" to "Search Results (?)"
- [x] Make the styling of the search box match the designs
- [x] Make the rows clickable and show in different colour
- [x] Error showing when using text search

**Contact Page**

- [x] Active tab on a Contact Page is slightly larger in the designs
- [x] Profile photo placement at the top when looking at individual (put it in a box)
- [x] Bring the little icons in plus put the summary like in the designs
- [x] Make the left hand side search box look like the designs. 
- [x] Have no pager for left hand search results
- [x] Create a new Personal Details tab which has the equivalent of the Individual data set details
- [x] Eventually there will be a "User Account" tab
- [x] The name at the top is currently the username, and should be real name
- [x] Remove dob from top summary
- [x] Fix the notes tab showing "page not found"
- [x] Adjust the alignment of the top summary information so that it looks like the designs (inc white border on photo)
- [x] The layout of the contact page has more 'spacing' around the edges in the design, can we adjust to match pls. Also the listings of people needs the id removing
- [x] Default profile image not showing at top of contact page when no profile image loaded.
- [x] Saving the notes goes to the wrong page
- [x] Saving the user account gets stuck on existing profile images being the wrong type
- [x] the tick of "This user has login details" hides/unhides the user/password fields is broken.
- [x] Remove the id from the left hand listings, and make it narrower
- [x] the mobile number is aligned with the bottom of the photo atm, on petes designes its not
- [x] Hide the summary and make the account page the default

**Not yet**
- [ ] Remove from the summary page any information that appears in the top, review whether or not we disable the summary page.
- [ ] Issue with Organisations being able to have user accounts. - This tab needs to be hidden, but we still need to be able to edit the logo.
- [ ] Decide what to do about local/contact (both enabled by Drupal for default)
- [ ] Review Security of Contacts listings and Contacts pages.

**Comment by adrianharvey** [comment]
![Demo logo](http://start.upshiftpartners.com/wp-content/uploads/2015/02/0008-cloudtech.jpg)

**Comment by andrewbelcher** [comment]
I have moved to a 'native font stack', the idea being it will render nicely and quickly in all browsers on all systems. It's what the new version of Bootstrap use, what github use and others. Pete's font is one of the fonts in that list.
