### ISSUE TITLE
Implement the ability to easily create managed tabs / forms (Data)

### ISSUE THREAD

**Issue by jamieaa64** [FreelyGive/contacts#27]
Managed Tabs:

Creating a New Tab:
Manage Contacts Dashboard permission. 
Grey Tab if you have that permission
Add tab is only option
Name of the tab, creates a profile type for this
Store in contacttype/role (is it person or Org)
Restructure tabs stuff so that it is not hard coded and generated based off le. 1 for each profile type, 1 for user account and 1 for summary. criteria rules.

Manage Fields on this tab. (List of manage tabs in top cog)
Takes us to the manage fields on this profile type.

### Tasks
- [x] Re-work tabs to show one for each profile type + summary + user account.
- [x] Switch to edit forms if we have access.
- [x] Change `ContactProfileAccessCheck` to use data stored in profile type roles.
- [x] Add a permission to administer the contacts dashboard (may already be done).
- [x] Add an 'Add tab' action in a manage group with grey cog.
- [x] Add tab form is a simplified version of the profile form showing only name/machine name.
- [x] Store the contact type in 3rd party settings of the profile.
- [x] Add links to edit/manage fields for each existing profile type
- [x] Staff -> Staff Admin
- [x] Redirect issue on saving individual tab
- [x] Configure height is strange in chrome
- [x] Improve wording of the Roles field on profile types
- [x] The configure tabs links are being cached

---------------------
- We want to build a way to make it so that you can go from the party dashboard to the configuration of profiles intuitively (Both, managing fields on a specific dataset and creating a new dataset)
- We want to hackily make it so that creating a new dataset automatically creates a new tab
- We want to make it so that if you click "Add tab/ dataset" from the party dashboard it knows what context you're looking at and prefills all the information required (so if you're looking at individuals it will attach it to an individual). We want it to then automatically create all the permissions needed.
- We then want the button as to whether people can edit their own profile, to add a "tab" to the "User dashboard" depending on whether or not this has been selected.

**Create new data**
- [ ] Fields on datasets
- [ ] New data sets

**Change the display of data**
- [ ] Layout of datasets + fields + tabs
