### ISSUE TITLE
Create ability to have contextual views on Contacts

### ISSUE THREAD

**Issue by adrianharvey** [FreelyGive/contacts#31]
Contextual Views/Hats
i.e. Customer Service & HR
Put the tabs at the top for contexts. Shown automatically for the roles they have)
Extra information in each profile type for which context it is shown for.

Adding a new role in normal drupal way, define the contexts to be show we edit the profile type.

Add tab defaults to showing for current context.

Editing contexts is done via tab which has links to edit profile type.

### Tasks
- [x] Store which contexts a profile type should show for including a UI to change it
  - 'Contact dashboard contexts in which this profile is visible'
- [x] Show 'context' tabs for each non calculated role the logged in user has
  - Store active context in the session.
  - Default to the first available context.
- [x] Add an access check for the tabs which checks the active context & profile type (non profile type tabs or profile types with no settings show to all).
- [x] Make add tab default to the active context.
